### ISSUE TITLE
error from load_dataset()

### ISSUE THREAD

**Issue by jinz2014** [McGill-NLP/feedbackqa#8]
Hi,
Can you reproduce the error ?

```
from datasets import load_dataset
r = load_dataset("McGill-NLP/feedbackQA")["train"]
```

/home/user/miniconda3/envs/trustllm/lib/python3.9/site-packages/datasets/load.py:1486: FutureWarning: The repository for McGill-NLP/feedbackQA contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/McGill-NLP/feedbackQA
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
/home/user/.cache/huggingface/datasets/downloads/8c4cae661a2aae10dee7ff50c9a5c5cd83aff73715f7520ecaeab3cf555dd2f2/feedback_test.json
Generating train split:   0%|                                                                               | 0/5660 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/trustllm/lib/python3.9/site-packages/datasets/builder.py", line 1748, in _prepare_split_single
    for key, record in generator:
  File "/home/user/.cache/huggingface/modules/datasets_modules/datasets/McGill-NLP--feedbackQA/20c8f938f417c88303bb7041cea9554c1d14667686d7d7c5dda83dd4f39e5dc4/feedbackQA.py", line 109, in _generate_examples
    with open(filepath, encoding="utf-8") as f:
  File "/home/user/miniconda3/envs/trustllm/lib/python3.9/site-packages/datasets/streaming.py", line 75, in wrapper
    return function(*args, download_config=download_config, **kwargs)
  File "/home/user/miniconda3/envs/trustllm/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 1219, in xopen
    return open(main_hop, mode, *args, **kwargs)
NotADirectoryError: [Errno 20] Not a directory: '/home/user/.cache/huggingface/datasets/downloads/8c4cae661a2aae10dee7ff50c9a5c5cd83aff73715f7520ecaeab3cf555dd2f2/feedback_train.json'

**Comment by cslizc** [comment]
@jinz2014 Hi, could you plz try `r = load_dataset("McGill-NLP/feedbackQA", trust_remote_code=True)`? It's working well on my end.

**Comment by ddahlmeier** [comment]
i am getting a NonMatchingChecksumError when trying to download the dataset via the HF dataset client

ratings = load_dataset("McGill-NLP/feedbackQA")["train"]

...
NonMatchingChecksumError: Checksums didn't match for dataset source files:
['[https://drive.google.com/uc?export=download&id=14KV6yKgdjzb6fbFzshGuNvEp9zGv_gol']](https://drive.google.com/uc?export=download&id=14KV6yKgdjzb6fbFzshGuNvEp9zGv_gol%27%5D)


When I try
> r = load_dataset("McGill-NLP/feedbackQA", trust_remote_code=True)
I get a the error TypeError: BuilderConfig.__init__() got an unexpected keyword argument 'trust_remote_code'

Maybe this option was removed by HF

**Comment by jinz2014** [comment]
@cslizc 

I am sorry that I missed your response. I got the same error. Since there is no error on your end, the error is related to my environment and software updates. Thanks.

**Comment by ddahlmeier** [comment]
The error is not always reproducible. I tried again today and today it worked fine
>feedbackQA_train = load_dataset("McGill-NLP/feedbackQA")["train"]

**Comment by mskim8717** [comment]
Hello, 

@xhluca 
I have learned about llm-as-a-judge and I found cookbook on huggingface. 
https://huggingface.co/learn/cookbook/llm_judge

I want to use this dataset, but I failed download it from yesterday night.
I tried to almost all cases through getting information online. 

Could you help me download your dataset?

`data = load_dataset("McGill-NLP/feedbackQA", trust_remote_code=True, download_mode='force_redownload')`


Traceback (most recent call last):
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1608, in _prepare_split_single
    for key, record in generator:
  File "/Users/minsoo/.cache/huggingface/modules/datasets_modules/datasets/McGill-NLP--feedbackQA/20c8f938f417c88303bb7041cea9554c1d14667686d7d7c5dda83dd4f39e5dc4/feedbackQA.py", line 109, in _generate_examples
    with open(filepath, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/streaming.py", line 75, in wrapper
    return function(*args, download_config=download_config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/utils/file_utils.py", line 944, in xopen
    return open(main_hop, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/Users/minsoo/.cache/huggingface/datasets/downloads/3fd9d8b80db4e8ce3de049be3beae23e75ccf024624d7daf007ced34c6f446d4/feedback_train.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/m_/46f3cb3d6yxcg6zw2pl97q4h0000gn/T/ipykernel_5544/3627405356.py", line 2, in <module>
    ratings = load_dataset("McGill-NLP/feedbackQA", trust_remote_code=True)['train']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/load.py", line 2084, in load_dataset
    builder_instance.download_and_prepare(
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 925, in download_and_prepare
    self._download_and_prepare(
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1649, in _download_and_prepare
    super()._download_and_prepare(
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1001, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1487, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/Users/minsoo/PycharmProjects/llm-as-a-judge/.venv/lib/python3.11/site-packages/datasets/builder.py", line 1644, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

**Comment by xhluca** [comment]
I think this is a regression error wtih huggingface. perhaps you could open an issue in their repo? Thanks!
